# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-05-04 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(max_length=200)),
                ('incorrect_answer_1', models.CharField(max_length=200)),
                ('incorrect_answer_2', models.CharField(max_length=200)),
                ('incorrect_answer_3', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Room'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Room'),
        ),
    ]
