# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-11-03 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.SlugField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='room',
        ),
        migrations.AddField(
            model_name='contestant',
            name='complete',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='code',
            field=models.SlugField(default='changeme', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='questions',
            field=models.ManyToManyField(to='quiz.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='quiz.Tag'),
        ),
    ]
