# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionVault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(max_length=200)),
                ('incorrect_answer_1', models.CharField(max_length=200)),
                ('incorrect_answer_2', models.CharField(max_length=200)),
                ('incorrect_answer_3', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
    ]
