# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20170504_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='incorrect_answer_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='incorrect_answer_2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='incorrect_answer_3',
        ),
        migrations.AddField(
            model_name='question',
            name='questions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.QuestionVault'),
        ),
    ]
