# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-11-10 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20171107_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
