# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-10-22 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20170504_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='complete',
            field=models.IntegerField(default=1),
        ),
    ]
