# Generated by Django 2.0.1 on 2018-06-16 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20171110_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='questions',
        ),
    ]
