# Generated by Django 2.0.1 on 2018-06-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_room_questions_m2m_intermidiary_with_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='questions',
            field=models.ManyToManyField(through='quiz.RoomQuestions', to='quiz.Question'),
        ),
    ]
