# Generated by Django 2.0.1 on 2018-06-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_room_questions_m2m_field_accessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='latest_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
