# Generated by Django 2.0.1 on 2018-06-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_contestant_latest_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomquestions',
            name='state',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CURRENT', 'Current'), ('COMPLETE', 'Complete')], default='Pending', max_length=10),
        ),
    ]
