# Generated by Django 2.0.1 on 2018-09-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_default_question_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_question_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomquestions',
            name='question_number',
            field=models.IntegerField(auto_created=True, default=0),
        ),
    ]
